const Discord = require("discord.js");
const { MessageEmbed } = require("discord.js");
const api = require('blueapi.js');

module.exports = {
name: "circle",
aliases: ["krug"],
category: "Images",
description: "Circle Command",
usage: "z!circle <@user>",
run: async(client, message, args, prefix) => {
  const user = message.mentions.users.first() || message.author;

  message.lineReplyNoMention(`**This Will Take a Little Bit Of Time To Load! **<@${message.author.id}>`).then(m => {
  setTimeout(function() {
  m.delete()
  }, 350);
  })
  let image = await api.image.circle(user.displayAvatarURL({ dynamic: true, format: 'png' }), { frames: 40 }).catch(e => {
    message.lineReplyNoMention(`**An Error Has Occured!**\n\`${e}\``)
  });

  let file = new Discord.MessageAttachment(image, "circle.png");

/*
  const embed = new MessageEmbed()
  .setFooter(`${client.user.username} ${new Date().getFullYear()} ©`)
  .setImage(`${image}`)
  message.lineReplyNoMention(`**Petpet Image**`, embed)
  */
 message.lineReplyNoMention(`${user} **Here Is Your Circle Profile Picture! Generated By: **<@${message.author.id}>`, file)
}
}
