const Discord = require("discord.js");
const { MessageEmbed } = require("discord.js");
const api = require('blueapi.js');

module.exports = {
name: "pet",
aliases: ["petpet"],
category: "Images",
description: "Petpet Command",
usage: "z!pet <@user>",
run: async(client, message, args, prefix) => {
  const user = message.mentions.users.first() || message.author;

  message.lineReplyNoMention(`**This Will Take a Little Bit Of Time To Load! **<@${message.author.id}>`).then(m => {
  setTimeout(function() {
  m.delete()
  }, 1600);
  })
  //let circle = api.image.circle(user.displayAvatarURL({ dynamic: true, format: 'png' }));
  let image = await api.image.petpet(await api.image.circle(user.displayAvatarURL({ dynamic: true, format: 'png' })), { frames: 40 }).catch(e => {
    message.lineReplyNoMention(`**An Error Has Occured!**\n\`${e}\``)
  });

  let file = new Discord.MessageAttachment(image, "petpet.gif");

/*
  const embed = new MessageEmbed()
  .setFooter(`${client.user.username} ${new Date().getFullYear()} ©`)
  .setImage(`${image}`)
  message.lineReplyNoMention(`**Petpet Image**`, embed)
  */
 message.lineReplyNoMention(`${user} **Here Is Your Gif! Generated By: **<@${message.author.id}>`, file)
}
}
