const Discord = require("discord.js");
const { MessageEmbed } = require("discord.js");
const api = require('blueapi.js');

module.exports = {
name: "trigger",
aliases: ["triggered"],
category: "Images",
description: "Triggered Command",
usage: "z!trigger <@user>",
run: async(client, message, args, prefix) => {
  const user = message.mentions.users.first() || message.author;

  message.lineReplyNoMention(`**This Will Take a Little Bit Of Time To Load! **<@${message.author.id}>`).then(m => {
  setTimeout(function() {
  m.delete()
  }, 2000);
  })
  let image = await api.image.trigger(user.displayAvatarURL({ dynamic: true, format: 'png' })).catch(e => {
    message.lineReplyNoMention(`**An Error Has Occured!**\n\`${e}\``)
  });

  let file = new Discord.MessageAttachment(image, "trigger.gif");

/*
  const embed = new MessageEmbed()
  .setFooter(`${client.user.username} ${new Date().getFullYear()} ©`)
  .setImage(`${image}`)
  message.lineReplyNoMention(`**Petpet Image**`, embed)
  */
 message.lineReplyNoMention(`${user} **Here Is Your Gif! Generated By: **<@${message.author.id}>`, file)
}
}
