const Discord = require("discord.js");
const { MessageEmbed } = require("discord.js");

module.exports = {
    name: "createinvite",
    aliases: ["crinvite"],
    ownerOnly: false,
    cooldown: 86400000,
    category: "Utility",
    usage: "z!createinvite",
    description: "Create Instant Invite Command",
    run: async (client, message, args, prefix) => {
      if(!message.member.hasPermission("CREATE_INSTANT_INVITE")) {
      let embed = new MessageEmbed()
      .setColor(`#000001`)
      .setDescription(`**You Don't Have The "Create Invite" Permission!**`);

      return message.lineReplyNoMention(embed);
      }
     if (!message.guild.me.hasPermission("CREATE_INSTANT_INVITE")) {
       let embed1 = new MessageEmbed()
       .setColor(`#000001`)
       .setDescription(`**I Don't Have The "Create Invite" Permission!**`);

       return message.lineReplyNoMention(embed1);
     }
    let channel = message.channel;
    channel.createInvite({unique: true}).then(invite => {
    var d = Date(Date.now());
    a = d.toString()
    const success = new MessageEmbed()
    .setColor("#000001")
    .setDescription(`**Here Is The Invite Link For ${message.guild.name}: [Invite](https://discord.gg/${invite.code})**`)
    .setFooter(`This Invite Was Generated Using ${client.user.username} ${new Date().getFullYear()} ©`)
    message.lineReplyNoMention(`**This Invite Was Generated By ${message.author.tag} (ID: ${message.author.id})\nCreation Date:**\`${a}\`\n**Invite Code: ${invite.code}**`, success)
    })
    }
  }
