const { readFileSync } = require("fs");
const Discord = require("discord.js");
const { MessageEmbed } = require("discord.js");
const sourcebin = require("sourcebin_js");
const { site, extension, inviteurl } = require("../../config.json")

module.exports = {
  name: "code",
  ownerOnly: true,
  description: "Shows Code Of a Command!",
  usage: "z!code <category> <command>",
  category: "Owner",
  run: async (client, message, args, prefix) => {

    /*
    if(message.author.id != "484701017015975936") return message.lineReplyNoMention("An Error Has Occured | You Are Not The Bot Owner!")
    */

    /*
      const owner1 = client.users.cache.get("484701017015975936")
      const owner2 = client.users.cache.get("643009255372488704")

      let owners = ["484701017015975936", "643009255372488704"];

      if(!owners.includes(message.author.id)) return message.lineReplyNoMention(notowner)
   */
  /*
   const notowner = new MessageEmbed()
   .setDescription(`**An Error Has Occured | You Are Not The Bot Owner!**`)
   .setColor(`#000001`)

   const owner1 = client.users.cache.get("484701017015975936")
   const owner2 = client.users.cache.get("643009255372488704")

   let owners = ["484701017015975936", "643009255372488704"];

   if(!owners.includes(message.author.id)) return message.lineReplyNoMention(notowner)
*/
   let category = args[0]
   let command = args[1]
   let choice = args[2];

   if(!category){
     const choosecat = new MessageEmbed()
     .setColor("#000001")
     .setDescription(`**Please Select a Category!**`)
    return message.lineReplyNoMention(choosecat)
   }

   if(!command){
     const choosecom = new MessageEmbed()
     .setColor("#000001")
     .setDescription(`**Please Select a Command!**`)
    return message.lineReplyNoMention(choosecom)
   }
   if (!choice)  {
     return message.lineReplyNoMention(`**Choose An Option (sourcebin/file)**`)
   }

   if(category == 'Information'){
     category = 'Info';
   }

   if(category == 'information'){
     category = 'Info';
   }

   if(category == 'Moderation'){
     category = 'Mod';
   }

   if(category == 'moderation'){
     category = 'Mod';
   }
   if (choice === 'sourcebin') {
           sourcebin.create([
               {
                   name: `${client.user.username}'s Code For The Command: ${command.charAt(0).toUpperCase() + command.slice(1)}.js (${prefix}${command})`,
                   content: `/*\nBot: ${client.user.username}\nInvite: ${site}.${extension}/${inviteurl}/\nCategory: ${category.charAt(0).toUpperCase() + category.slice(1)}\nCommand: ${prefix}${command.charAt(0).toUpperCase() + command.slice(1)}\nFile Name: ${command.charAt(0).toUpperCase() + command.slice(1)}.js\nPath: ./commands/${category.charAt(0).toUpperCase() + category.slice(1)}/${command}.js\n*/\n\n` + readFileSync(`./commands/${category.charAt(0).toUpperCase() + category.slice(1)}/${command}.js`).toString() + `\n\n/*\nThis Is The Code For ${command.charAt(0).toUpperCase() + command.slice(1)}.js | This Command Is Owned By ${client.user.username} (${site}.${extension}) \nIf You Somehow Found This Sourcebin Please Don't Use Our Code Or Atleast Give Us Credit!\n*/`, //content: readFileSync(`./commands/${category.charAt(0).toUpperCase() + category.slice(1)}/${command.charAt(0).toUpperCase() + command.slice(1)}.js`).toString()
                   languageId: 'js'
               }
             ], {
                  title: `This Sourcebin Was Generated By ${message.author.tag} The Owner Of ${client.user.username}!`,
                  description: `You Can Invite ${client.user.username} Here => ${site}.${extension}/${inviteurl}`
            }).then(src => {
             const ssembed = new MessageEmbed()
             .setColor("#000001")
             .setDescription(`**${command.charAt(0).toUpperCase() + command.slice(1)}.js Code =>** **[Here](${src.url})**`)
               message.lineReplyNoMention(ssembed)
           }).catch(e => {
               let errembed = new MessageEmbed()
                   .setColor("#000001")
                   .setDescription(`An Error Has Occured\n${e}`);

               message.lineReplyNoMention(errembed);
           });
}

if (choice === 'file') {
  let content = `/*\nBot: ${client.user.username}\nInvite: ${site}.${extension}/${inviteurl}/\nCategory: ${category.charAt(0).toUpperCase() + category.slice(1)}\nCommand: ${prefix}${command.charAt(0).toUpperCase() + command.slice(1)}\nFile Name: ${command.charAt(0).toUpperCase() + command.slice(1)}.js\nPath: ./commands/${category.charAt(0).toUpperCase() + category.slice(1)}/${command}.js\n*/\n\n` + readFileSync(`./commands/${category.charAt(0).toUpperCase() + category.slice(1)}/${command}.js`).toString() + `\n\n/*\nThis Is The Code For ${command.charAt(0).toUpperCase() + command.slice(1)}.js | This Command Is Owned By ${client.user.username} (${site}.${extension}) \nIf You Somehow Found This Sourcebin Please Don't Use Our Code Or Atleast Give Us Credit!\n*/`; //content: readFileSync(`./commands/${category.charAt(0).toUpperCase() + category.slice(1)}/${command.charAt(0).toUpperCase() + command.slice(1)}.js`).toString()
  let attachment = Buffer.from(content);
  message.lineReplyNoMention({
  files: [
  {
  name: `${command}.js`,
  attachment: attachment
  }]})
}
 }}
